language: ruby
rvm:
  - 1.9.3

before_script:
  - "bundle exec rake db:create db:migrate"
  - "bundle exec rake db:test:prepare" 

notifications:
  email:
    - mary.cutrali@hungrymachine.com
    - horace.williams@hungrymachine.com
    - austen.ito@hungrymachine.com

branches:
  only:
    - master
