get_latest_tweets:
  every: ["300s"]
  class: GetLatestTweets
  description: "resuqes!"

get_latest_gits:
  every: ["300s"]
  class: GetLatestGits
  description: "resuqes!"

get_latest_grams:
  every: ["300s"]
  class: GetLatestGrams
  description: "resuqes!"

get_latest_subscription_posts:
  every: ["60s"]
  class: GetLatestSubscriptionPosts
  description: "zoot!"
