tweet:
  every: '5m'
  class: SubscriptionJob
  queue: subscription
  description: "This will gather tweets every 5 min for the user"

gist: 
  every: '30s'
  class: SubscriptionJob
  queue: subscription 
  description: "This will gather new github events every 5 min for the user"