source 'https://rubygems.org'

gem 'rails', '3.2.3'
gem 'devise'
gem 'sqlite3'

gem 'jquery-rails'
gem "twitter-bootstrap-rails"
gem 'simple_form'

group :test, :development do
  gem 'ruby_gntp'
  gem "rspec-rails", "~> 2.0"
  gem "capybara"
  gem 'guard'
  gem 'fabrication'
  gem 'faker'
  gem 'launchy'
  gem 'simplecov'
end

group :production do
  gem 'pg'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
